# Site settings
title: Electronics Corner | Thinkering with hardware
description: "Thinkering with hard-firm-soft ware"
url: "http://www.hshah89.github.io"
author:
  name: "Harit"
  email: "harit26+blog@gmail.com"
  url: "http://www.hshah89.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: markdown
source: .
destination: ./_site
permalink: /:title
paginate: 25
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"
copyright: "&copy 2020"

# Options
custom_header: true
custom_nav_footer: true
reverse: true
