title: Electronics Corner
email: harit26+blog@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Thinkering with electronics
baseurl: "hshah89.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  hshah89

# Build settings
markdown: kramdown
remote_theme: chesterhow/tale

permalink:      /:year-:month-:day/:title
paginate:       5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme